# Auto-generated by .github/workflows/release.yml.
# Hand-edits will be overwritten on the next release.
class SmtpTestTool < Formula
  desc "Cross-platform SMTP / IMAP / POP3 connectivity tester with IT-actionable diagnostics"
  homepage "https://github.com/StruisICT/smtp-test-tool"
  version "0.2.1"
  license any_of: ["MIT", "Apache-2.0"]

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/StruisICT/smtp-test-tool/releases/download/v0.2.1/smtp-test-tool-aarch64-apple-darwin.tar.gz"
    sha256 "29706f8292ac109a46453f2843c16f6c3edb9721f9f849ef16dbde6e29316bbd"
  elsif OS.mac?
    url "https://github.com/StruisICT/smtp-test-tool/releases/download/v0.2.1/smtp-test-tool-x86_64-apple-darwin.tar.gz"
    sha256 "6a0e2e1da1ddb71a58499a920588724680bd62d9eb4077bd6360b9062520504d"
  elsif OS.linux?
    url "https://github.com/StruisICT/smtp-test-tool/releases/download/v0.2.1/smtp-test-tool-x86_64-unknown-linux-gnu.tar.gz"
    sha256 "f517ba4737f91984fc01b4e7d5673d9ef6fa7431431ceaad87a0dad0b2407fb4"
  end

  def install
    bin.install "smtp-test-tool"
    bin.install "smtp-test-tool-gui" if File.exist?("smtp-test-tool-gui")
  end

  test do
    assert_match "smtp-test-tool", shell_output("#{bin}/smtp-test-tool --version")
  end
end
